export default {
    "s&p500": [
        "Apple",
        "Microsoft",
        "Alphabet",
        "Alphabet",
        "Amazon.com",
        "Berkshire Hathaway",
        "NVIDIA",
        "Tesla",
        "Meta Platforms",
        "UnitedHealth Group",
        "Visa",
        "Exxon Mobil",
        "Johnson & Johnson",
        "Walmart",
        "JPMorgan Chase & Co.",
        "Procter & Gamble",
        "Mastercard",
        "Eli Lilly and",
        "Home Depot",
        "Chevron",
        "AbbVie",
        "Merck & Co., Inc.",
        "Broadcom",
        "Coca-Cola",
        "PepsiCo",
        "PepsiCo",
        "Oracle",
        "Pfizer",
        "Bank of America",
        "Costco Wholesale",
        "Thermo Fisher Scientific",
        "Cisco Systems",
        "McDonald's",
        "NIKE",
        "Salesforce",
        "Danaher",
        "T-Mobile US",
        "Walt Disney",
        "Abbott Laboratories",
        "Adobe",
        "Linde",
        "United Parcel Service",
        "Texas Instruments",
        "Advanced Micro Devices",
        "Accenture",
        "Verizon Communications",
        "Comcast",
        "NextEra Energy",
        "Philip Morris International",
        "Wells Fargo & Company",
        "Morgan Stanley",
        "Raytheon Technologies",
        "Bristol-Myers Squibb",
        "Netflix",
        "QUALCOMM",
        "AT&T",
        "Honeywell International",
        "Intel",
        "Amgen",
        "Lowe's Companies",
        "Boeing",
        "Lockheed Martin",
        "American Express",
        "Union Pacific",
        "Intuit",
        "ConocoPhillips",
        "Deere & Company",
        "Starbucks",
        "International Business Machines",
        "Caterpillar",
        "Elevance Health",
        "S&P Global",
        "Prologis",
        "Medtronic",
        "Stryker",
        "Applied Materials",
        "The Goldman Sachs Group",
        "Charles Schwab",
        "General Electric",
        "Gilead Sciences",
        "BlackRock",
        "CVS Health",
        "Analog Devices",
        "American Tower",
        "Booking",
        "Mondelez International",
        "ServiceNow",
        "Automatic Data Processing",
        "TJX Companies",
        "Citigroup",
        "Estée Lauder Companies",
        "Intuitive Surgical",
        "PayPal",
        "Regeneron Pharmaceuticals",
        "Altria Group",
        "The Cigna Group",
        "Progressive",
        "Chubb",
        "Marsh & McLennan Companies",
        "Zoetis",
        "Vertex Pharmaceuticals",
        "Duke Energy",
        "Southern",
        "Target",
        "Illinois Tool Works",
        "HCA Healthcare",
        "Boston Scientific",
        "Lam Research",
        "Fiserv",
        "Northrop Grumman",
        "CME Group",
        "Becton, Dickinson and",
        "Equinix",
        "Schlumberger",
        "Eaton",
        "Waste Management",
        "Activision Blizzard",
        "Humana",
        "Micron Technology",
        "Air Products and Chemicals",
        "AON",
        "EOG Resources",
        "Colgate-Palmolive",
        "General Dynamics",
        "CSX",
        "Moderna",
        "Synopsys",
        "3M",
        "Cadence Design Systems",
        "Crown Castle",
        "Sherwin-Williams",
        "FedEx",
        "Marathon Petroleum",
        "Intercontinental Exchange",
        "Moody's",
        "Monster Beverage",
        "KLA",
        "Charter Communications",
        "Occidental Petroleum",
        "Public Storage",
        "Freeport-McMoRan",
        "U.S. Bancorp",
        "Arista Networks",
        "Hershey",
        "The PNC Financial Services Group",
        "O'Reilly Automotive",
        "Keurig Dr Pepper",
        "Edwards Lifesciences",
        "Marriott International",
        "Fortinet",
        "General Mills",
        "Valero Energy",
        "Dollar General",
        "American Electric Power",
        "General Motors",
        "McKesson",
        "Norfolk Southern",
        "Dominion Energy",
        "Emerson Electric",
        "Kraft Heinz",
        "NXP Semiconductors",
        "Sempra Energy",
        "Amphenol",
        "Roper Technologies",
        "Ford Motor",
        "Chipotle Mexican Grill",
        "AutoZone",
        "Microchip Technology",
        "Motorola Solutions",
        "DexCom",
        "Cintas",
        "Ecolab",
        "Phillips 66",
        "MSCI",
        "Pioneer Natural Resources",
        "Autodesk",
        "MetLife",
        "Kimberly-Clark",
        "Exelon",
        "Exelon",
        "Las Vegas Sands",
        "Republic Services",
        "Archer-Daniels-Midland",
        "Trane Technologies",
        "Truist Financial",
        "Realty Income",
        "Corteva",
        "Agilent Technologies",
        "Parker-Hannifin",
        "IDEXX Laboratories",
        "TE Connectivity",
        "Constellation Brands",
        "Paychex",
        "Travelers Companies",
        "Newmont",
        "Arthur J. Gallagher & Co.",
        "Biogen",
        "TransDigm Group",
        "Aflac",
        "L3Harris Technologies",
        "Sysco",
        "Xcel Energy",
        "Kinder Morgan",
        "Carrier Global",
        "Old Dominion Freight Line",
        "Hilton Worldwide",
        "Nucor",
        "Hess",
        "PACCAR",
        "IQVIA",
        "Yum! Brands",
        "Illumina",
        "Johnson Controls International",
        "DOW",
        "Ross Stores",
        "Warner Bros. Discovery",
        "American International Group",
        "Williams Companies",
        "Centene",
        "Capital One Financial",
        "Simon Property Group",
        "Bank of New York Mellon",
        "Consolidated Edison",
        "onsemi",
        "Welltower",
        "Kroger",
        "D.R. Horton",
        "W.W. Grainger",
        "Copart",
        "Otis Worldwide",
        "Mettler-Toledo International",
        "Cummins",
        "Rockwell Automation",
        "Electronic Arts",
        "VICI Properties",
        "AMETEK",
        "DuPont de Nemours",
        "AmerisourceBergen",
        "Fidelity National Information Services",
        "ResMed",
        "Dollar Tree",
        "Devon Energy",
        "Lennar",
        "Ameriprise Financial",
        "Fastenal",
        "WEC Energy Group",
        "Brown-Forman",
        "Cognizant Technology Solutions",
        "Digital Realty Trust",
        "Public Service Enterprise Group",
        "Aptiv",
        "PPG Industries",
        "Prudential Financial",
        "Walgreens Boots Alliance",
        "Verisk Analytics",
        "Corning",
        "Allstate",
        "SBA Communications",
        "Keysight Technologies",
        "HP",
        "LyondellBasell Industries",
        "Baker Hughes",
        "ANSYS",
        "Halliburton",
        "ONEOK",
        "Eversource Energy",
        "Zimmer Biomet",
        "Global Payments",
        "Edison International",
        "American Water Works",
        "Nasdaq",
        "Ulta Beauty",
        "United Rentals",
        "Tractor Supply",
        "CDW",
        "Constellation Energy",
        "Enphase Energy",
        "State Street",
        "Equifax",
        "Align Technology",
        "West Pharmaceutical Services",
        "Albemarle",
        "T. Rowe Price Group",
        "Discover Financial Services",
        "Gartner",
        "Willis Towers Watson Public",
        "Monolithic Power Systems",
        "CBRE Group",
        "Genuine Parts",
        "FirstEnergy",
        "Diamondback Energy",
        "AvalonBay Communities",
        "eBay",
        "Fortive",
        "Quanta Services",
        "Ameren",
        "Kellogg",
        "Entergy",
        "DTE Energy",
        "Equity Residential",
        "Extra Space Storage",
        "Vulcan Materials",
        "Weyerhaeuser",
        "Ingersoll Rand",
        "Delta Air Lines",
        "International Flavors & Fragrances",
        "Hormel Foods",
        "Alexandria Real Estate Equities",
        "Church & Dwight",
        "Tyson Foods",
        "M&T Bank",
        "The Hartford Financial Services Group",
        "VeriSign",
        "Martin Marietta Materials",
        "PPL",
        "Take-Two Interactive Software",
        "McCormick & Company, Incorporated",
        "Teledyne Technologies",
        "Dover",
        "Clorox",
        "Hologic",
        "Baxter International",
        "Raymond James",
        "Laboratory Co. of America",
        "Garmin",
        "Garmin",
        "Garmin",
        "CenterPoint Energy",
        "Hewlett Packard Enterprise",
        "Skyworks Solutions",
        "Darden Restaurants",
        "Cardinal Health",
        "CMS Energy",
        "NVR",
        "Southwest Airlines",
        "Coterra Energy",
        "Rollins",
        "Ventas",
        "Waters",
        "STERIS",
        "FOX",
        "Omnicom Group",
        "J.B. Hunt Transport Services",
        "Xylem",
        "Northern Trust",
        "Principal Financial Group",
        "Fifth Third Bancorp",
        "Best Buy",
        "Mid-America Apartment Communities",
        "Conagra Brands",
        "Cooper Companies",
        "Westinghouse Air Brake Technologies",
        "Regions Financial",
        "Paycom Software",
        "Cincinnati Financial",
        "Expeditors International of Washington",
        "Atmos Energy",
        "Incyte",
        "Teradyne",
        "Teradyne",
        "Teradyne",
        "IDEX",
        "J. M. Smucker",
        "Ball",
        "Howmet Aerospace",
        "EPAM Systems",
        "FOX",
        "W. R. Berkley",
        "Campbell Soup",
        "Broadridge Financial Solutions",
        "Amcor",
        "Royal Caribbean Cruises",
        "FactSet Research Systems",
        "PerkinElmer",
        "MGM Resorts International",
        "Live Nation Entertainment",
        "Brown & Brown",
        "Molina Healthcare",
        "SolarEdge Technologies",
        "Huntington Bancshares",
        "AES",
        "Citizens Financial Group",
        "Zebra Technologies",
        "MarketAxess",
        "Quest Diagnostics",
        "Iron Mountain",
        "FMC",
        "Mosaic",
        "LKQ",
        "Expedia Group",
        "Jacobs Solutions",
        "United Airlines",
        "PTC",
        "Lamb Weston",
        "Bio-Rad Laboratories",
        "CF Industries",
        "FLEETCOR Technologies",
        "Evergy",
        "Tyler Technologies",
        "Avery Dennison",
        "Textron",
        "Essex Property Trust",
        "Pool",
        "Alliant Energy",
        "Alliant Energy",
        "Marathon Oil",
        "Cboe Global Markets",
        "NetApp",
        "Franklin Resources",
        "Etsy",
        "Everest Re Group",
        "Interpublic Group of Companies",
        "UDR",
        "Paramount Global",
        "Seagate Technology",
        "Loews",
        "PulteGroup",
        "Synchrony Financial",
        "Leidos",
        "Snap-on",
        "Wynn Resorts",
        "Catalent",
        "Trimble",
        "International Paper",
        "Stanley Black & Decker",
        "Nordson",
        "Akamai Technologies",
        "Packaging Co. of America",
        "Bio-Techne",
        "Healthpeak Properties",
        "NiSource",
        "Viatris",
        "Western Digital",
        "C.H. Robinson Worldwide",
        "Celanese",
        "Masco",
        "Teleflex",
        "Domino's Pizza",
        "Host Hotels & Resorts",
        "Host Hotels & Resorts",
        "Kimco Realty",
        "Camden Property Trust",
        "Molson Coors Beverage",
        "KeyCorp",
        "Ceridian HCM",
        "BorgWarner",
        "Jack Henry & Associates",
        "Match Group",
        "Juniper Networks",
        "Henry Schein",
        "Globe Life",
        "A. O. Smith",
        "APA",
        "Charles River Laboratories International",
        "Regency Centers",
        "Tapestry",
        "Qorvo",
        "Carnival Co. &",
        "Eastman Chemical",
        "Caesars Entertainment",
        "News",
        "News",
        "American Airlines Group",
        "Allegion",
        "CarMax",
        "Pinnacle West Capital",
        "F5",
        "Universal Health Services",
        "Pentair",
        "V.F.",
        "Boston Properties",
        "Huntington Ingalls Industries",
        "DENTSPLY SIRONA",
        "Robert Half International",
        "Bath & Body Works",
        "Federal Realty Investment Trust",
        "Ralph Lauren",
        "NRG Energy",
        "Advance Auto Parts",
        "Invesco",
        "Whirlpool",
        "Generac",
        "DaVita",
        "WestRock",
        "Hasbro",
        "Sealed Air",
        "Mohawk Industries",
        "Comerica",
        "Assurant",
        "Organon & Co.",
        "Norwegian Cruise Line",
        "Norwegian Cruise Line",
        "DXC Technology",
        "Alaska Air Group",
        "DISH Network",
        "Newell Brands",
        "Newell Brands",
        "PVH",
        "Zions Bancorporation, National Association",
        "PENN Entertainment",
        "First Republic Bank",
        "Lincoln National",
        "Vornado Realty Trust",
        "Lumen Technologies",
        "Embecta",
    ],
};
