export default {
    productCategories: [
        "electronics",
        "clothing & apparel",
        "home & garden",
        "health & beauty",
        "toys & games",
        "sports & outdoors",
        "automotive",
        "pet supplies",
        "books & media",
        "office supplies",
    ],
    randomProducts: [
        "Acoustic Guitar",
        "Air Conditioner",
        "Alarm Clock",
        "Backpack",
        "Bathrobe",
        "BBQ Grill",
        "Bedding Set",
        "Blender",
        "Bluetooth Speaker",
        "Board Game",
        "Bookcase",
        "Bowling Ball",
        "Boxing Gloves",
        "Bread Maker",
        "Camera",
        "Camping Tent",
        "Carpet Cleaner",
        "Cat Tree",
        "Ceiling Fan",
        "Cell Phone",
        "Chainsaw",
        "Charcoal Grill",
        "Coffee Maker",
        "Comforter Set",
        "Computer Monitor",
        "Cookware Set",
        "Cordless Drill",
        "Couch",
        "Cross Trainer",
        "Desk",
        "Dining Table",
        "Dishwasher",
        "Dog Bed",
        "Dryer",
        "Electric Bike",
        "Electric Blanket",
        "Electric Kettle",
        "Electric Scooter",
        "Espresso Machine",
        "Exercise Bike",
        "Fishing Rod",
        "Fitness Tracker",
        "Floor Lamp",
        "Food Processor",
        "Football",
        "Freezer",
        "Frying Pan",
        "Gaming Chair",
        "Garden Hose",
        "Gas Grill",
        "Hair Dryer",
        "Handheld Vacuum",
        "Headphones",
        "Hiking Boots",
        "Home Theater System",
        "Humidifier",
        "Ice Cream Maker",
        "Iron",
        "Juicer",
        "Keyboard",
        "Laptop",
        "Lawn Mower",
        "Leather Jacket",
        "LED TV",
        "Luggage",
        "Mattress",
        "Meditation Cushion",
        "Microwave",
        "Mixing Bowls",
        "Mountain Bike",
        "Mouse",
        "Nespresso Machine",
        "Office Chair",
        "Oven",
        "Painting Set",
        "Paper Shredder",
        "Patio Furniture",
        "Pencil Set",
        "Piano",
        "Ping Pong Table",
        "Pool Table",
        "Portable Air Conditioner",
        "Power Bank",
        "Printer",
        "Projector",
        "Quilt",
        "Racquetball Racquet",
        "Refrigerator",
        "Resistance Bands",
        "Rice Cooker",
        "Road Bike",
        "Robot Vacuum",
        "Rowing Machine",
        "Running Shoes",
        "Sewing Machine",
        "Showerhead",
        "Skateboard",
        "Ski Boots",
        "Sleeping Bag",
        "Slow Cooker",
        "Smart Watch",
        "Sneakers",
        "Snowboard",
        "Soccer Ball",
        "Sofa Bed",
        "Soundbar",
        "Stand Mixer",
        "Steam Iron",
        "Steam Mop",
        "Steamer",
        "Stereo System",
        "Storage Ottoman",
        "Stroller",
        "Surround Sound System",
        "Table Lamp",
        "Table Tennis Paddle",
        "Tea Kettle",
        "Toaster",
        "Toilet",
        "Treadmill",
        "Tripod",
        "Vacuum Cleaner",
        "Vitamix Blender",
        "Waffle Maker",
        "Wall Clock",
        "Washing Machine",
        "Water Bottle",
        "Water Filter",
        "Weight Bench",
        "Wine Cooler",
        "Wireless Earbuds",
        "Yoga Mat",
    ],
    electronics: [
        "Apple iPhone 13",
        "Samsung Galaxy S21",
        "Sony PlayStation 5",
        "Xbox Series X",
        "LG CX OLED TV",
        "Sony WH-1000XM4 Headphones",
        "Sonos Beam Soundbar",
        "Bose QuietComfort Earbuds",
        "Nest Learning Thermostat",
        "Ring Video Doorbell Pro",
        "Arlo Pro 4 Security Camera",
        "DJI Mavic Air 2 Drone",
        "GoPro HERO10 Black",
        "Canon EOS R6 Camera",
        "Logitech C920 Webcam",
        "HyperX Cloud II Gaming Headset",
        "Razer DeathAdder Elite Gaming Mouse",
        "Corsair K95 RGB Platinum XT Keyboard",
        "ASUS ROG Swift PG279Q Gaming Monitor",
        "Dell XPS 13 Laptop",
        "Lenovo ThinkPad X1 Carbon Laptop",
        "Microsoft Surface Laptop 4",
        "HP Spectre x360 Laptop",
        "Samsung Galaxy Tab S7+ Tablet",
        "Apple iPad Air",
        "Amazon Kindle Paperwhite",
        "Fitbit Charge 5 Fitness Tracker",
        "Garmin Forerunner 945 GPS Watch",
        "Bose SoundLink Revolve+ Bluetooth Speaker",
        "JBL Flip 5 Portable Speaker",
        "UE Megaboom 3 Wireless Speaker",
        "Anker PowerCore 10000 Power Bank",
        "Belkin BoostCharge 10K Power Bank",
        "Apple AirPods Pro",
        "Samsung Galaxy Buds Pro",
        "Jabra Elite 85t Earbuds",
        "Sony SRS-XB43 Portable Speaker",
        "Logitech G502 HERO Gaming Mouse",
        "SteelSeries Arctis Pro Wireless Headset",
        "Elgato Stream Deck Mini",
        "Astro A50 Wireless Gaming Headset",
        "Beats Solo3 Wireless Headphones",
        "Bowers & Wilkins PX7 Wireless Headphones",
        "Shure Aonic 50 Wireless Headphones",
        "LG 34GN850-B Ultrawide Gaming Monitor",
        "Acer Predator X27 Gaming Monitor",
        "Samsung Odyssey G9 Gaming Monitor",
        "Microsoft Xbox Elite Wireless Controller Series 2",
        "DualShock 4 Wireless Controller for PlayStation 4",
        "Nintendo Switch Pro Controller",
        "Oculus Quest 2 Virtual Reality Headset",
        "HTC Vive Cosmos Elite VR Headset",
        "Samsung Galaxy Watch 4 Classic",
        "Apple Watch Series 7",
        "Garmin Venu 2S Smartwatch",
        "Fossil Gen 6 Smartwatch",
        "Roku Streaming Stick+",
        "Amazon Fire TV Stick 4K",
        "Chromecast with Google TV",
        "Nvidia Shield TV Pro",
        "WD Elements 1TB Portable External Hard Drive",
        "Samsung T5 500GB Portable SSD",
        "SanDisk Extreme Pro 128GB SD Card",
        "Logitech MX Master 3 Wireless Mouse",
        "Microsoft Ergonomic Keyboard",
        "Wacom Intuos Pro Creative Pen Tablet",
        "Apple Magic Mouse 2",
        "Sony WF-1000XM4 Earbuds",
        "Sennheiser Momentum True Wireless 2 Earbuds",
        "JBL Quantum 800 Gaming Headset",
        "Beyerdynamic DT 990 Pro Headphones",
        "Bose QuietComfort 35 II Wireless Headphones",
        "Vizio M-Series Quantum 4"
      ],
    "clothing & apparel": [
        "Levi's 501 Original Fit Jeans",
        "Adidas Originals Superstar Sneakers",
        "Converse Chuck Taylor All Star High Tops",
        "Nike Air Force 1 Low Sneakers",
        "New Balance 990v5 Running Shoes",
        "Vans Old Skool Skate Shoes",
        "Dr. Martens 1460 Combat Boots",
        "Timberland Classic 6-Inch Waterproof Boots",
        "The North Face Denali Fleece Jacket",
        "Patagonia Better Sweater Fleece Jacket",
        "Columbia Bugaboo Interchangeable Jacket",
        "Arc'teryx Atom LT Insulated Jacket",
        "Carhartt Duck Chore Coat",
        "Ralph Lauren Polo Shirt",
        "Tommy Hilfiger Classic Oxford Shirt",
        "Calvin Klein Modern Cotton T-Shirt",
        "Champion Reverse Weave Hoodie",
        "Hanes ComfortBlend EcoSmart Sweatshirt",
        "Nike Sportswear Tech Fleece Hoodie",
        "Under Armour Tech 2.0 Short Sleeve Shirt",
        "Lululemon ABC Pant",
        "Athleta Salutation Stash Pocket Leggings",
        "Nike Pro Tights",
        "Adidas Originals Tiro 19 Training Pants",
        "Patagonia Baggies Shorts",
        "The North Face Paramount Active Shorts",
        "Champion Mesh Shorts",
        "Levi's Trucker Jacket",
        "Columbia Steens Mountain Fleece Vest",
        "Puma Essentials Logo Tank Top",
        "Reebok Classics Vector Track Jacket",
        "Vineyard Vines Whale Shirt",
        "Bonobos Stretch Washed Chinos",
        "Banana Republic Slim Rapid Movement Denim",
        "J.Crew Ludlow Suit Jacket",
        "Topman Skinny Fit Suit Trousers",
        "Zara Basic Denim Jacket",
        "H&M Hooded Sweatshirt",
        "Uniqlo Ultra Light Down Jacket",
        "Gap Vintage Soft Pocket T-Shirt",
        "American Eagle Slim Straight Jeans",
        "Express 1MX Dress Shirt",
        "Forever 21 Floral Print Maxi Dress",
        "Free People Ottoman Tunic",
        "Urban Outfitters Ribbed Bodycon Midi Dress",
        "ASOS Design Tiered Midi Skirt",
        "Zara Faux Leather Biker Jacket",
        "Hollister Sherpa-Lined Parka",
        "Abercrombie & Fitch Sherpa-Lined Denim Jacket",
        "Levi's Original Trucker Jacket",
        "L.L.Bean Classic Ragg Wool Sweater",
        "Patagonia Synchilla Snap-T Pullover",
        "Columbia Steens Mountain Full Zip Fleece",
        "The North Face Venture 2 Rain Jacket",
        "Carhartt Midweight Hooded Sweatshirt",
        "Lululemon Define Jacket",
        "Nike Dri-FIT Tempo Running Shorts",
        "Under Armour HeatGear Armour Capri",
        "Adidas Originals 3-Stripes Leggings",
        "Reebok Workout Ready Mesh Tank Top",
        "Champion Powerblend Fleece Pullover Hoodie",
        "Hanes ComfortSoft Long Sleeve T-Shirt",
        "Gap Arch Logo Pullover Hoodie",
        "Forever 21 Striped Ribbed Knit Top",
        "American Eagle Tie-Dye Sweatshirt",
        "Express Slim Tapered Jeans",
        "Banana Republic Slim Traveler Pant"
      ],
    "home & garden": [
        "Dyson V11 Torque Drive Cordless Vacuum",
        "iRobot Roomba 960 Robot Vacuum",
        "Shark Navigator Lift-Away Professional Vacuum",
        "Bissell PowerEdge Pet Hardwood Floor Corded Vacuum",
        "Hoover Power Scrub Deluxe Carpet Cleaner",
        "Rug Doctor Deep Carpet Cleaner",
        "Le Creuset Signature Enameled Cast Iron Dutch Oven",
        "All-Clad Stainless Steel 10-Piece Cookware Set",
        "Cuisinart Classic Nonstick Hard-Anodized 14-Piece Cookware Set",
        "Lodge Cast Iron Skillet",
        "Calphalon Tri-Ply Stainless Steel 13-Piece Cookware Set",
        "Ninja Foodi Deluxe XL Pressure Cooker & Air Fryer",
        "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
        "Vitamix 5200 Blender",
        "KitchenAid Artisan Series 5-Quart Stand Mixer",
        "Breville Barista Express Espresso Machine",
        "Cuisinart 12-Cup Programmable Coffee Maker",
        "Keurig K-Elite Single Serve Coffee Maker",
        "Nespresso VertuoPlus Coffee and Espresso Maker",
        "Hamilton Beach Digital Air Fryer",
        "Ninja Foodi Power Pitcher Blender",
        "OXO Good Grips POP Container Set",
        "Rubbermaid Brilliance Food Storage Containers",
        "Simplehuman Stainless Steel Step Trash Can",
        "Bamboo Woven Storage Baskets",
        "Honey-Can-Do 10-Drawer Rolling Storage Cart",
        "Cotton Craft Handwoven Jute Area Rug",
        "Mohawk Home Strata Caravan Medallion Area Rug",
        "Safavieh Hudson Shag Collection Area Rug",
        "Tuft & Needle Original Mattress",
        "Casper Original Mattress",
        "Tempur-Pedic TEMPUR-Adapt Mattress",
        "Linenspa 8 Inch Memory Foam and Innerspring Hybrid Mattress",
        "Zinus 12 Inch Green Tea Memory Foam Mattress",
        "Boll & Branch Solid Hemmed Sheet Set",
        "Brooklinen Luxe Core Sheet Set",
        "Parachute Linen Sheet Set",
        "Threshold Performance 400 Thread Count Sheet Set",
        "Hotel Collection Primaloft Comforter",
        "Utopia Bedding Down Alternative Comforter",
        "The Company Store Legends Hotel Supima Cotton Bath Towels",
        "Snowe Honeycomb Bath Towel Set",
        "Rugs USA Jute Diamond Area Rug",
        "Pottery Barn PB Classic Belgian Flax Linen Curtain",
        "West Elm Belgian Flax Linen Duvet Cover",
        "Crate & Barrel Marin White Dinnerware Set",
        "CB2 Lunea Melamine White 18-Piece Dinnerware Set",
        "Williams Sonoma Open Kitchen Glassware Collection",
        "Anthropologie Glimmer Glassware Collection",
        "Williams Sonoma Open Kitchen Stainless Steel Utensils",
        "OXO Good Grips 3-Piece Mixing Bowl Set",
        "Nordic Ware Aluminum Baker's Half Sheet",
        "Crate & Barrel Stackable Glass Storage Jars",
        "Lodge Enameled Cast Iron Dutch Oven",
        "Anchor Hocking Glass Mixing Bowls",
        "Chicago Metallic Non-Stick 12-Cup Muffin Pan",
        "Wilton Perfect Results Premium Non-Stick Bakeware Set"
      ],
    "health & beauty": [
        "Clarisonic Mia Smart Sonic Facial Cleansing Brush",
        "Foreo Luna Mini 2 Facial Cleansing Brush",
        "Neutrogena Light Therapy Acne Spot Treatment",
        "Tria Beauty Hair Removal Laser 4X",
        "Braun Silk-épil 9 9-579 Epilator",
        "Philips Sonicare DiamondClean Smart Electric Toothbrush",
        "Oral-B Genius Pro 8000 Electric Toothbrush",
        "Waterpik Aquarius Professional Water Flosser",
        "Olay Regenerist Micro-Sculpting Cream",
        "La Roche-Posay Anthelios Sunscreen",
        "EltaMD UV Clear Facial Sunscreen",
        "Supergoop! Unseen Sunscreen SPF 40",
        "Kiehl's Ultra Facial Cream",
        "Drunk Elephant Protini Polypeptide Cream",
        "First Aid Beauty Ultra Repair Cream",
        "Laneige Water Sleeping Mask",
        "GlamGlow SuperMud Clearing Treatment",
        "Fresh Sugar Lip Treatment",
        "Burt's Bees Beeswax Lip Balm",
        "Aquaphor Healing Ointment",
        "Bioderma Sensibio H2O Micellar Water",
        "Thayers Witch Hazel Toner",
        "Mario Badescu Facial Spray with Aloe, Herbs and Rosewater",
        "The Ordinary Niacinamide 10% + Zinc 1%",
        "Sunday Riley Good Genes All-In-One Lactic Acid Treatment",
        "Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant",
        "Kate Somerville ExfoliKate Intensive Exfoliating Treatment",
        "Benefit Cosmetics Gimme Brow+ Volumizing Eyebrow Gel",
        "Anastasia Beverly Hills Brow Wiz",
        "Maybelline Great Lash Mascara",
        "L'Oreal Paris Voluminous Lash Paradise Mascara",
        "Fenty Beauty Pro Filt'r Soft Matte Longwear Foundation",
        "Nars Radiant Creamy Concealer",
        "Tarte Shape Tape Concealer",
        "Laura Mercier Translucent Loose Setting Powder",
        "Charlotte Tilbury Airbrush Flawless Finish Setting Powder",
        "Beautyblender Original Makeup Sponge",
        "Real Techniques Miracle Complexion Sponge",
        "Sephora Collection PRO Flawless Airbrush #56",
        "Sultra The Bombshell Oval Curling Wand",
        "Dyson Supersonic Hair Dryer",
        "ghd Platinum+ Styler",
        "Oribe Dry Texturizing Spray",
        "Living Proof Perfect Hair Day Dry Shampoo",
        "R+Co Dallas Thickening Spray",
        "Klorane Dry Shampoo with Oat Milk",
        "L'Occitane Shea Butter Hand Cream",
        "Weleda Skin Food",
        "Nécessaire The Body Wash",
        "Herbivore Botanicals Coco Rose Body Polish",
        "Kiehl's Creme de Corps Body Moisturizer",
        "Sol de Janeiro Brazilian Bum Bum Cream",
        "Lancôme La Vie est Belle Eau de Parfum",
        "Chanel Coco Mademoiselle Eau de Parfum",
        "Tom Ford Black Orchid Eau de Parfum",
        "Jo Malone London Wood Sage & Sea Salt Cologne",
        "Aesop Resurrection Aromatique Hand Wash",
      ],
    "toys & games": [
        "LEGO Star Wars Millennium Falcon 75192",
        "Barbie Dreamhouse Dollhouse with Pool, Slide and Elevator",
        "Hot Wheels Super Ultimate Garage Playset",
        "NERF Rival Prometheus MXVIII-20K Blaster",
        "Fisher-Price Think & Learn Code-a-Pillar Twist",
        "Sphero SPRK+ STEAM Educational Robot",
        "Osmo Genius Starter Kit for iPad",
        "Snap Circuits Jr. SC-100 Electronics Discovery Kit",
        "Kano Computer Kit Touch – Build and Code a Tablet",
        "littleBits Star Wars Droid Inventor Kit",
        "Anki Cozmo Robot",
        "Robo Wunderkind Robotics Kit",
        "LEGO Ideas NASA Apollo Saturn V 21309",
        "LEGO Boost Creative Toolbox 17101",
        "LEGO Super Mario Adventures with Mario Starter Course 71360",
        "Nintendo Switch Console",
        "PlayStation 5 Console",
        "Xbox Series X Console",
        "Pokemon TCG: Sword & Shield Elite Trainer Box",
        "Magic: The Gathering Core Set 2021 Booster Box",
        "Catan Board Game",
        "Pandemic Board Game",
        "Ticket to Ride Board Game",
        "Codenames Board Game",
        "Risk Board Game",
        "Bananagrams Word Game",
        "Exploding Kittens Card Game",
        "Cards Against Humanity Party Game",
        "Jenga Classic Game",
        "Operation Board Game",
        "Hungry Hungry Hippos Game",
        "Connect 4 Game",
        "Guess Who? Board Game",
        "Monopoly Classic Game",
        "Scrabble Game",
        "Clue Game",
        "Battleship Game",
        "The Game of Life Board Game",
        "Uno Card Game",
        "Settlers of Catan Board Game",
        "Carcassonne Board Game",
        "Gloomhaven Board Game",
        "Twister Game",
        'Chess Armory 15" Wooden Chess Set',
        "Jellycat Stuffed Animal",
        "Melissa & Doug Wooden Animal Magnets Set",
        "Hatchimals Pixies Crystal Flyers",
        "L.O.L. Surprise! OMG Remix Super Surprise",
        "LEGO Harry Potter Hogwarts Castle 71043",
        "LEGO Star Wars Death Star 10188",
        "LEGO Creator Expert Volkswagen T1 Camper Van 10220",
        "LEGO Technic Bugatti Chiron 42083",
        "LEGO Architecture Statue of Liberty 21042",
        "LEGO Classic Large Creative Brick Box 10698",
        "LEGO DUPLO My First Number Train 10847",
        "VTech KidiZoom Camera Pix",
        "Fisher-Price Little People Cuddle & Play Nursery",
        "Green Toys Ferry Boat with Mini Cars Bathtub Toy",
        "Hape Pound & Tap Bench with Slide Out Xylophone",
        "Melissa & Doug Deluxe Wooden Railway Train Set",
        "NERF Elite 2.0 Phoenix CS-6 Motorized Blaster",
        "Pokemon Pikachu Plush Stuffed Animal",
        "Funko Pop! Marvel: Avengers Endgame - Iron Man",
        "Barbie Dreamtopia Brush 'n Sparkle Unicorn",
        "Gund Baby Animated Flappy The Elephant Plush Toy",
        "Radio Flyer 4-in-1 Stroll 'N Trike"
          ],
    "sports & outdoors": [
        "Fitbit Charge 5 Fitness Tracker",
        "Garmin Forerunner 945 GPS Running Watch",
        "Apple Watch Series 7",
        "Bose QuietComfort Earbuds",
        "Powerbeats Pro Wireless Earbuds",
        "YETI Tundra 65 Cooler",
        "Coleman Sundome Tent",
        "Coleman Steel Creek Fast Pitch Dome Tent",
        "Intex Explorer K2 Kayak",
        "Pelican Trailblazer 100 NXT Kayak",
        "Osprey Packs Daylite Plus Daypack",
        "Gregory Mountain Products Baltoro 75 Backpack",
        "Hydro Flask Wide Mouth Water Bottle",
        "CamelBak Chute Mag Water Bottle",
        "Nalgene Wide Mouth Water Bottle",
        "Stanley Classic Vacuum Bottle",
        "ENO DoubleNest Hammock",
        "Tentsile Connect 2-Person Tree Tent",
        "Therm-a-Rest NeoAir XTherm Sleeping Pad",
        "Coleman Palmetto Cool Weather Sleeping Bag",
        "The North Face Cat's Meow Sleeping Bag",
        "Columbia Sportswear Bugaboo II Fleece Interchangeable Jacket",
        "The North Face Resolve 2 Jacket",
        "Patagonia Better Sweater 1/4-Zip Fleece Jacket",
        "Columbia Sportswear Arcadia II Rain Jacket",
        "The North Face Apex Bionic 2 Jacket",
        "Salomon X Ultra 3 GTX Hiking Shoes",
        "Merrell Moab 2 Waterproof Hiking Shoes",
        "Keen Targhee III Waterproof Hiking Shoes",
        "Vasque Breeze III GTX Hiking Shoes",
        "La Sportiva Wildcat Trail Running Shoes",
        "Brooks Ghost 14 Running Shoes",
        "HOKA ONE ONE Clifton 8 Running Shoes",
        "Nike Air Zoom Pegasus 39 Running Shoes",
        "ASICS Gel-Kayano 28 Running Shoes",
        "Wilson Federer Tennis Racquet",
        "Babolat Pure Aero Tennis Racquet",
        "Head Graphene 360+ Speed MP Tennis Racquet",
        "Yonex Astrel 105 Tennis Racquet",
        "Rawlings 5150 USA Youth Baseball Bat",
        "Easton Ghost Advanced Fastpitch Softball Bat",
        "DeMarini CF Zen BBCOR Baseball Bat",
        "Mizuno MVP Prime SE Baseball Glove",
        "Rawlings Heart of the Hide PRO303-6JBT Baseball Glove",
        "Wilson A2000 1788 Baseball Glove",
        "Rawlings Pro Preferred PROS205-4C Baseball Glove",
        "Nike Phantom GT Club FG Soccer Cleats",
        "Adidas Predator Freak .1 FG Soccer Cleats",
        "Puma Future Z 1.1 FG/AG Soccer Cleats",
        "New Balance Fresh Foam 1080v11 Running Shoes",
        "Under Armour HOVR Phantom 2 Running Shoes",
        "Brooks Adrenaline GTS 22 Running Shoes",
        "Salomon Speedcross 5 Trail Running Shoes",
        "Garmin Edge 530 GPS Cycling Computer",
        "Wahoo Elemnt Bolt GPS Cycling Computer",
        "Lezyne Super GPS Cycling Computer",
        "Garmin Approach S62 Golf Watch",
        "Bushnell Tour V5 Shift Golf Laser Rangefinder",
        "Titleist Pro V1 Golf Balls",
        "Callaway Chrome Soft Golf"
      ],
    "automotive": [
        "Garmin DriveSmart 65 GPS Navigator",
        "Apple CarPlay Double Din Car Stereo",
        "Sony XAV-AX7000 Double Din Car Stereo",
        "Pioneer AVH-W4500NEX Double Din Car Stereo",
        "BOSS Audio Systems BVCP9685A Double Din Car Stereo",
        "Anker Roav DashCam A1",
        "Garmin Dash Cam 56",
        "Nextbase 522GW Dash Cam",
        "AUKEY DR02 Dash Cam",
        "Yakima Skybox Carbonite Cargo Box",
        "Thule Force XT Cargo Box",
        "Rhino Rack Pioneer Platform Roof Rack",
        "Yakima JetStream Crossbars",
        "Thule Aeroblade Edge Crossbars",
        "Meguiar's Ultimate Wash & Wax",
        "Chemical Guys Butter Wet Wax",
        "Turtle Wax Hybrid Solutions Ceramic Spray Coating",
        "CarGuys Hybrid Wax Sealant",
        "Armor All Original Protectant",
        "303 Aerospace Protectant",
        "Chemical Guys InnerClean Interior Quick Detailer",
        "Carfidant Ultimate Interior Cleaner",
        "Meguiar's Carpet & Upholstery Cleaner",
        "Tuff Stuff Multi-Purpose Foam Cleaner",
        "Rain-X Latitude Water Repellency Wiper Blades",
        "Bosch Icon Wiper Blades",
        "Michelin Stealth Ultra Wiper Blades",
        "RainEater G3 Wiper Blades",
        "Castrol Edge Full Synthetic Motor Oil",
        "Mobil 1 Full Synthetic Motor Oil",
        "Pennzoil Platinum Full Synthetic Motor Oil",
        "Royal Purple High Performance Synthetic Motor Oil",
        "K&N High Performance Air Filter",
        "Bosch Premium Oil Filter",
        "FRAM Extra Guard Air Filter",
        "Gates Timing Belt Kit",
        "Dayco Timing Belt Kit",
        "Mishimoto Radiator",
        "Koyo Aluminum Radiator",
        "Denso Oxygen Sensor",
        "Bosch Oxygen Sensor",
        "NGK Iridium IX Spark Plugs",
        "Denso Platinum TT Spark Plugs",
        "Continental Elite Serpentine Belt",
        "Gates Micro-V Serpentine Belt",
        "CURT Class III Trailer Hitch",
        "Draw-Tite Class III Trailer Hitch",
        "Reese Towpower Class III Trailer Hitch",
        "Yakima Ridgeback Hitch Mount Bike Rack",
        "Thule T2 Pro XT Hitch Mount Bike Rack",
        "Kuat NV 2.0 Hitch Mount Bike Rack",
        "CURT Basket Style Cargo Carrier",
        "Pro Series Hitch Cargo Carrier",
        "Reese Explore Hitch Cargo Carrier",
        "K&N Performance Air Intake Kit",
        "Injen Power-Flow Air Intake System",
        "Volant Cold Air Intake Kit",
        "Borla Performance Exhaust System",
        "Magnaflow Performance Exhaust System",
        "Flowmaster American Thunder Exhaust System",
        "DiabloSport inTune i3 Performance Tuner",
        "Superchips Flashpaq F5 Performance Tuner",
        "Bully Dog GT Platinum Performance Tuner",
        "Optima RedTop AGM Battery",
        "Odyssey Extreme Series AGM Battery",
        "DieHard Platinum AGM Battery",
        "NOCO Genius Boost Plus Jump Starter",
        "Stanley J5C09 Jump Starter",
        "Schumacher SC1281 Jump Starter",
        "WeatherTech Floor Mats"
      ],
    "pet supplies": [
        "Blue Buffalo Life Protection Formula Dry Dog Food",
        "Hill's Science Diet Dry Dog Food",
        "Merrick Grain-Free Dry Dog Food",
        "Royal Canin Adult Dry Dog Food",
        "Purina Pro Plan Sensitive Skin & Stomach Dry Dog Food",
        "Blue Buffalo Wilderness Grain-Free Dry Cat Food",
        "Hill's Science Diet Dry Cat Food",
        "Merrick Grain-Free Dry Cat Food",
        "Royal Canin Adult Dry Cat Food",
        "Purina Pro Plan Focus Indoor Care Dry Cat Food",
        "KONG Classic Dog Toy",
        "Chuckit! Ultra Ball",
        "Nylabone Dura Chew Textured Ring",
        "Outward Hound Hide-A-Squirrel Puzzle Toy",
        "KONG Puppy Toy",
        "Benebone Wishbone Dog Chew Toy",
        "Nylabone Power Chew Dura Chew Textured Ring",
        "West Paw Zogoflex Hurley Dog Bone",
        "Frisco Plush Squeaking Unicorn Dog Toy",
        "PetSafe Automatic Ball Launcher",
        "PetSafe Drinkwell Platinum Pet Fountain",
        "PetSafe ScoopFree Self-Cleaning Cat Litter Box",
        "Bissell PowerEdge Pet Hardwood Floor Corded Vacuum",
        "Shark Navigator Lift-Away Professional Upright Vacuum",
        "Dyson Cyclone V10 Animal Cordless Vacuum",
        "iRobot Roomba 692 Robot Vacuum",
        "Veken Pet Fountain",
        "PetSafe Simply Feed Automatic Feeder",
        "PetSafe Healthy Pet Simply Feed Automatic Feeder",
        "PetSafe Smart Feed Automatic Feeder",
        "K&H Pet Products Thermo-Kitty Heated Cat Bed",
        "Frisco Ortho Textured Plush Bolster Sofa Dog Bed",
        "PetFusion Orthopedic Memory Foam Dog Bed",
        "Frisco Heavy Duty Double Door Dog Crate",
        "MidWest Homes for Pets XXL Giant Dog Crate",
        "PetSafe Freedom Aluminum Pet Door",
        "PetSafe Plastic Pet Door",
        "PetSafe Wall Entry Pet Door",
        "Frisco Fold & Carry Single Door Dog Crate",
        "MidWest Homes for Pets Folding Metal Exercise Pen",
        "Frisco 72-Inch Cat Tree",
        "Go Pet Club 62-Inch Cat Tree",
        "AmazonBasics Cat Tree with Cave",
        "Arm & Hammer Clump & Seal Platinum Cat Litter",
        "World's Best Cat Litter",
        "Dr. Elsey's Ultra Premium Clumping Cat Litter",
        "Tidy Cats 4-in-1 Strength Clumping Cat Litter",
        "Rocco & Roxie Professional Strength Stain & Odor Eliminator",
        "Nature's Miracle Stain & Odor Remover",
        "Simple Solution Extreme Stain & Odor Remover",
        "Bissell ProHeat 2X Revolution Max Clean Pet Pro Full-Size Carpet Cleaner",
        "Rug Doctor Deep Carpet Cleaner",
        "Hoover Power Scrub Elite Pet Upright Carpet Cleaner",
        "Frisco Dog Poop Bags",
        "Earth Rated Dog Poop Bags",
        "Pogi's Poop Bags",
        "Frisco Training & Potty Pads",
        "AmazonBasics Dog Waste Bags with Dispenser",
        "Nylabone Power Chew Dura Chew Textured Ring",
        "KONG Classic Dog Toy"
      ],
    "books & media": [
        "The Silent Patient by Alex Michaelides",
        "The Girl with the Dragon Tattoo by Stieg Larsson",
        "To Kill a Mockingbird by Harper Lee",
        "1984 by George Orwell",
        "The Great Gatsby by F. Scott Fitzgerald",
        "The Alchemist by Paulo Coelho",
        "The Hunger Games by Suzanne Collins",
        "Harry Potter and the Sorcerer's Stone by J.K. Rowling",
        "The Lord of the Rings by J.R.R. Tolkien",
        "A Song of Ice and Fire by George R.R. Martin",
        "Becoming by Michelle Obama",
        "Educated by Tara Westover",
        "Bad Blood: Secrets and Lies in a Silicon Valley Startup by John Carreyrou",
        "Sapiens: A Brief History of Humankind by Yuval Noah Harari",
        "The 7 Habits of Highly Effective People by Stephen R. Covey",
        "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear",
        "Thinking, Fast and Slow by Daniel Kahneman",
        "The Lean Startup: How Today’s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses by Eric Ries",
        "The Art of War by Sun Tzu",
        "The Book of Five Rings by Miyamoto Musashi",
        "The Tao of Pooh by Benjamin Hoff",
        "The Power of Now by Eckhart Tolle",
        "Man's Search for Meaning by Viktor E. Frankl",
        "Born a Crime: Stories from a South African Childhood by Trevor Noah",
        "Homo Deus: A Brief History of Tomorrow by Yuval Noah Harari",
        "The New Jim Crow: Mass Incarceration in the Age of Colorblindness by Michelle Alexander",
        "The Immortal Life of Henrietta Lacks by Rebecca Skloot",
        "The Catcher in the Rye by J.D. Salinger",
        "Pride and Prejudice by Jane Austen",
        "Jane Eyre by Charlotte Bronte",
        "Wuthering Heights by Emily Bronte",
        "The Picture of Dorian Gray by Oscar Wilde",
        "Dracula by Bram Stoker",
        "Frankenstein by Mary Shelley",
        "The Adventures of Sherlock Holmes by Arthur Conan Doyle",
        "The War of the Worlds by H.G. Wells",
        "The Time Machine by H.G. Wells",
        "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
        "The Lord of the Flies by William Golding",
        "Brave New World by Aldous Huxley",
        "Fahrenheit 451 by Ray Bradbury",
        "The Martian by Andy Weir",
        "Ready Player One by Ernest Cline",
        "The Da Vinci Code by Dan Brown",
        "The Girl on the Train by Paula Hawkins",
        "Gone Girl by Gillian Flynn",
        "The Help by Kathryn Stockett",
        "The Fault in Our Stars by John Green",
        "The Nightingale by Kristin Hannah",
        "Little Fires Everywhere by Celeste Ng",
        "Where the Crawdads Sing by Delia Owens",
        "The Immortalists by Chloe Benjamin",
        "The Dutch House by Ann Patchett",
        "The Water Dancer by Ta-Nehisi Coates",
        "The Testaments by Margaret Atwood",
        "The Nickel Boys by Colson Whitehead"
      ],
    "office supplies": [
        "HP Laserjet Pro M15w Wireless Laser Printer",
        "Canon PIXMA TR4520 Wireless All in One Photo Printer",
        "Logitech MX Master 3 Advanced Wireless Mouse",
        "Microsoft Surface Keyboard",
        "Apple Magic Keyboard",
        "Lamicall Adjustable Phone Stand",
        "TaoTronics LED Desk Lamp",
        "HUANUO Lap Laptop Desk",
        "VIVO Dual LCD Monitor Desk Mount Stand",
        "AmazonBasics Mesh Desk Organizer",
        "ErgoFoam Ergonomic Foot Rest",
        "UPLIFT Desk V2 Bamboo Standing Desk",
        "Everlasting Comfort Memory Foam Seat Cushion",
        "Scotch Heavy Duty Shipping Packaging Tape",
        "Post-it Super Sticky Notes",
        "Sharpie Permanent Markers",
        "BIC Round Stic Xtra Life Ballpoint Pens",
        "Paper Mate Flair Felt Tip Pens",
        "AmazonBasics Legal/Wide Ruled 8-1/2 by 11-3/4 Legal Pad",
        "Five Star Advance Spiral Notebook",
        "Moleskine Classic Notebook",
        "Rocketbook Fusion Smart Reusable Notebook",
        "Swingline Electric Stapler",
        "Brother P-Touch Label Maker",
        "Fellowes Powershred 79Ci 100% Jam Proof Cross-Cut Paper Shredder",
        "Microsoft Office 365 Personal Subscription",
        "Adobe Creative Cloud Subscription",
        "HP OfficeJet Pro 9015e Wireless All-in-One Printer",
        "Apple MacBook Air with M1 Chip",
        "Dell XPS 13 Laptop",
        "ASUS Chromebook Flip C434 2-in-1 Laptop",
        "Samsung Galaxy Tab S7 FE 5G Tablet",
        "Logitech C920x Pro HD Webcam",
        "Bose QuietComfort 35 II Wireless Bluetooth Headphones",
        "Jabra Speak 710 Wireless Bluetooth Speaker",
        "Elgato Stream Deck",
        "Blue Yeti USB Microphone",
        "Audio-Technica AT2020USB+ Cardioid Condenser USB Microphone",
        "BenQ GW2270 22-Inch 1080p LED Monitor",
        "Samsung T7 Portable SSD",
        "SanDisk Extreme Pro Portable SSD",
        "Seagate Expansion Desktop 16TB External Hard Drive",
        "Microsoft Surface Pro 7",
        "Apple iPad Pro",
        "Logitech MX Anywhere 3 Wireless Mouse",
        "Apple Magic Mouse 2",
        "Parker Jotter Originals Ballpoint Pen Collection",
        "Paper Mate InkJoy Gel Pens",
        "Sharpie Fine Point Permanent Markers",
        "AmazonBasics Pre-sharpened Wood Cased #2 HB Pencils",
        "AmazonBasics Mesh Desk Drawer Office Organizer",
        "SimpleHouseware Mesh Desk Organizer with Sliding Drawer",
        "Mind Reader 3-Shelf Printer Cart",
        "FITUEYES Height Adjustable Standing Desk Converter",
        "Ergotron WorkFit-TL Sit-Stand Desktop Workstation",
        "Victor High Rise Collection Adjustable Standing Desk Converter",
        "AmazonBasics Comfort Foot Rest",
        "Everlasting Comfort Lumbar Support Pillow",
        "ComfiLife Gel Enhanced Seat Cushion",
        "iClever Bluetooth Keyboard",
        "Anker PowerExtend USB Power Strip",
        "Belkin 12-Outlet Power Strip Surge Protector"
      ],
};
