export default {
    cats: [
        "Abyssinian",
        "American Bobtail",
        "American Curl",
        "American Shorthair",
        "American Wirehair",
        "Balinese",
        "Bengal",
        "Birman",
        "Bombay",
        "British Shorthair",
        "Burmese",
        "Burmilla",
        "Calico",
        "Chartreux",
        "Chausie",
        "Cornish Rex",
        "Cymric",
        "Devon Rex",
        "Domestic Long Hair",
        "Domestic Medium Hair",
        "Domestic Shorthair",
        "Egyptian Mau",
        "Exotic Shorthair",
        "Havana",
        "Himalayan",
        "Japanese Bobtail",
        "Javanese",
        "Korat",
        "LaPerm",
        "Maine Coon",
        "Manx",
        "Munchkin",
        "Nebelung",
        "Norwegian Forest Cat",
        "Ocicat",
        "Oriental Short Hair",
        "Persian",
        "Pixiebob",
        "Ragamuffin",
        "Ragdoll",
        "Russian Blue",
        "Scottish Fold",
        "Selkirk Rex",
        "Siamese",
        "Siberian",
        "Singapura",
        "Snowshoe",
        "Somali",
        "Sphynx / Hairless Cat",
        "Tabby",
        "Tonkinese",
        "Tortoiseshell",
        "Toyger",
        "Turkish Angora",
        "Turkish Van",
        "Tuxedo",
        "York Chocolate",
    ],
};
